### ISSUE TITLE
Error when using exporter

### ISSUE THREAD

**Issue by jvillasante** [polaris64/modus-exporter#2]
Hello,

This project is awesome, I can now use the modus themes everywhere, thanks!
I just installed emacs-mac (https://github.com/railwaycat/homebrew-emacsmacport) and using doom. When I call `modus-exporter-insert-theme-colours-at-point` I get this error `modus-exporter-export-theme-tmux: Symbol’s value as variable is void: modus-operandi-theme-override-colors-alist`.

Any ideas?

**Comment by polaris64** [comment]
Hi there!

Thanks for the kind words!

I started this project quite a while ago, before version 1.0 of `modus-themes` I think. Since then, Protesilaos has changed quite a bit about how the themes work, so this library is no longer compatible with the latest versions.

I was planning on updating it, but then Protesilaos [released his own exporter](https://protesilaos.com/codelog/2021-02-22-modus-themes-exporter/). As he is the creator of the themes I decided that there's not much point now keeping this library up to date.

So hopefully you should be able to use his exporter instead. You've reminded me though that I should add a message to the README to state this too!

Let me know if there are any issues with his exporter and I can potentially take a look into updating this version or perhaps merging my work with his.
